project_id = "fyhnbmexusojuyrikxfm"

[functions.parse-document]
verify_jwt = false

[functions.upload-document]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.chat-intent]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false
